version: '3.7'
volumes:
  mysql_data:
services:
  # Database
  mysql:
    image: mysql:8.0.23
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    expose:
      - 3306
    ports:
      - 3306:3306

  # Keycloak
  keycloak:
    image: jboss/keycloak:12.0.2
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
